# Generated by Django 2.2.12 on 2020-09-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200925_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
    ]
