# Generated by Django 2.2.12 on 2020-09-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
