# Generated by Django 2.2.12 on 2020-09-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_store_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regions',
        ),
    ]
